language: scala
jdk:
  - oraclejdk8
scala:
   - 2.11.8
branches:
  only:
    - master
    - feature/crypto
    - feature/rlpRefactor
    - phase/2/txHashValidation
    - feature/messageVersioning
    - feature/spongycastleUpgrade
script:
    - sbt test

